### ISSUE TITLE
Please provide instruction how to run it.

### ISSUE THREAD

**Issue by tonual** [saddam213/OnnxStack#1]
```
r@mini OnnxStack % ls
Assets                          OnnxStack.Console               OnnxStack.StableDiffusion       README.md
LICENSE                         OnnxStack.Core                  OnnxStack.sln
r@mini OnnxStack % dotnet run --project OnnxStack.Console/OnnxStack.Console.csproj
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'OnnxStack.Console, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
r@mini OnnxStack % dotnet --version
7.0.308
r@mini OnnxStack % 

```

dotnet build was succesful

**Comment by saddam213** [comment]
Unfortunately im not sure how to run .NET apps on OSX

For Linux I use:
`dotnet publish /OnnxStack.Console --configuration debug --self-contained --runtime linux-x64 --output ./build/release`

Run (chmod my be required)
`./OnnxStack.Console`

Not sure if its the same for OSX

However the console app is really just a code basic example, the same example can be found here [Example Code](https://github.com/saddam213/OnnxStack/blob/master/OnnxStack.StableDiffusion/README.md)

**Comment by tonual** [comment]
Thank you for the hint!
With very few changes the project builds and runs on OSX, in particular M1/M2 silicon with CoreML support (neural engine).
Here is a reference branch:
https://github.com/tonual/OnnxStack/tree/CoreML

To build and run:

`dotnet build`
'dotnet publish OnnxStack.Console --configuration debug --self-contained --runtime osx-arm64 --output ./build/debug'
'run --project ./OnnxStack.Console'

**Comment by saddam213** [comment]
Thats awesome news

I will merge in your changes and fix up the tokenizer path stuff and hopefully this will work out of the box for you

Thanks for testing, legendary!!
