### ISSUE TITLE
Safetensors/ckpt conversion or loading

### ISSUE THREAD

**Issue by waylaa** [saddam213/OnnxStack#113]
Is there a way to convert (preferably on the fly) and load a safetensors or ckpt file?

**Comment by saddam213** [comment]
At the moment this is not currently possible unfortunately :(

I am currently working on a new project `TensorStack` wthich will replace `OnnxStack` eventually, this is a c# safetensors inference library using [Tensor.Net](https://github.com/SciSharp/Tensor.NET)

I hope to have a working repo of this in the next few months, this will have a much wider range of usable models compared to onnx

**Comment by waylaa** [comment]
That's good to know. By the way, do you know why it's such a hit or miss and a hassle to convert models especially stable diffusion ones to onnx? onnx seems promising but it doesnt have much of an adoption.

**Comment by saddam213** [comment]
I'm not sure, I have come to a development stand still on stable diffusion because none of the new animation or video models have been released on onnx like the others

That is the main reasons I'm switching to the safetensors format

**Comment by waylaa** [comment]
Have you considered making the new project public or will you do it in a couple of months as you said?

**Comment by saddam213** [comment]
yeah at the moment its just a bunch of snippets/experiments on parsing safetensor files to a c# tensor or array

The stable diffusion code itself will be pretty much copy/pasta, its just the interfacing with safetensor models I have to solve

Once I have something that resembles a project/solution I will upload, as I'm gonna need a lot of help on this one as its a lot harder than onnxstack

**Comment by waylaa** [comment]
That's good to know.
