### ISSUE TITLE
WebUI does not support multi-models or pipelines

### ISSUE THREAD

**Issue by saddam213** [saddam213/OnnxStack#21]
WebUI has fallen behind due to the inclusion of the WPF UI

I am wondering if we even need to keep it, other OS's already have many choices for Stable Diffusion so I think people using OnnxStack on linux and mac will be low

Perhaps time to scrap this project and replace with an API instead, easier to maintain, will still be cross-platform, then other people can make a WebUI or integrate the API into existing SD UI's

Or even go the other direction, add auth etc and make it a fully usable website for creating mid-journey style websites, allowing people to monetize their GPUs if they want

Pros: 
1. Cross-Platfrom
2. Server/Client Based, backend can be installed on GPU server
3. ASP.NET Core, so auth can easily be added for a Public facing website

Cons:
1. Server/Client Based, security concerns, xss, etc
2. Image handling is way harder on web, upload, download etc

Thoughts?

**Comment by Amin456789** [comment]
hmm, do u mean to keep standalone gui [the one that has the dark mode] and cancel webui [the one needs browser] ?
that is a nice idea, browsers always use more ram so sending all the power to the standalone gui is much much better imo, not to mention it is very beautiful now!

**Comment by saddam213** [comment]
> hmm, do u mean to keep standalone gui [the one that has the dark mode] and cancel webui [the one needs browser] ? that is a nice idea, browsers always use more ram so sending all the power to the standalone gui is much much better imo, not to mention it is very more portable and it is very beautiful now!

They are very different types of applications, so both have major benefits in different scenarios

**Comment by Amin456789** [comment]
true, honestly i love this gui with the dark mode more than anything out there in stable diffusion world right now! i think many will agree, i mean the casual users like me
but everybody hast a taste. let's hear their opinion too

**Comment by saddam213** [comment]
The WebUI have 8 skins, 4 dark 4 light, but how it look is not whats important, its how servers use OnnxStack not desktop users

I have severs with GPUs, the windows app is useless, unless I use it on the server, which you don't do

The WebUI is server/client based, so you setup the web on your server then you can connect and use it form many other PCs at the same time, like mid-journey

so as you can see, its much more powerful than the desktop app, but just not for how you use it.

**Comment by jdluzen** [comment]
The Uno project may be a close to drop-in replacement here. It is designed to be cross platform but keep mostly the same API from WinUI.

**Comment by Amin456789** [comment]
oh u right Adam, didn't see that point, lots of users wanna be server side too. maybe work on them both? gotta be spend more time to mention both, but hey a little update here and a little update there will be cool for the both world.

**Comment by jdluzen** [comment]
I really enjoy native apps, but that is a personal preference.
Blazor could be an option if that is the way forward. Uno can also target WASM.

**Comment by saddam213** [comment]
> The Uno project may be a close to drop-in replacement here. It is designed to be cross platform but keep mostly the same API from WinUI.

Im probably faster/better at Web than WPF, so if it was the other way around it would suit :p
 
This is my first WPF app in about 10 years, and the rust is real deep, lol, but forgot how cool XAML was!!

**Comment by saddam213** [comment]
> I really enjoy native apps, but that is a personal preference. Blazor could be an option if that is the way forward. Uno can also target WASM.

Yeah, native apps are way better if you are running a local setup, so the WPF is here to stay

**Comment by jdluzen** [comment]
> Im probably faster/better at Web than WPF, so if it was the other way around it would suit :p
I'm the opposite 😁
> This is my first WPF app in about 10 years, and the rust is real deep, lol, but forgot how cool XAML was!!
Couldn't tell, thought it was WinUI for a while until this thread. I didn't know official WPF wasn't ported to Core/net6. XAML is really nice.

**Comment by Amin456789** [comment]
u already did a great favor to the stable diffusion community! even if u stop updating wpf app i will still use this one :D
at the end, go for and do what is easier and better that u think

**Comment by saddam213** [comment]
yeah they added it to .NET Core, but its still windows only, But you still get all the other .NET Core goodies

**Comment by saddam213** [comment]
> > Im probably faster/better at Web than WPF, so if it was the other way around it would suit :p
> 
> I'm the opposite 😁
> 
> > This is my first WPF app in about 10 years, and the rust is real deep, lol, but forgot how cool XAML was!!
> 
> Couldn't tell, thought it was WinUI for a while until this thread. I didn't know official WPF was ported to Core/net6. XAML is really nice.

Yeah they added it to .NET Core, but its weird, still windows only, but you still still get the benefits of .NET Core

**Comment by jdluzen** [comment]
> But its still about 200lines of code to change the TitleBar color, lol Microsoft man

I never want to deal with the Win32 message pump again!

**Comment by Amin456789** [comment]
@saddam213 something i just realized Adam. i forgot how hard and time consuming is coding and all i was thinking was cool features on the gui and working on the gui is making u to not reach ur goals faster

i am not a technical guy so i can't understand most of what u guys just said, but please go after what u desire! that api backend thing, at some point someone will come and update the gui for us,

thanks for all u did and do man!

**Comment by JohnClaw** [comment]
Please, don't cancel WPF UI.

**Comment by Amin456789** [comment]
> Please, don't cancel WPF UI.

agree john, i just deleted two other apps that i was using after i got lcm fp16 working here, onnxstack is the better one, and it will get lots of more fans in the future. but at the end it's Adam choice, he did a great job already for free for us. it will be great if he continue wpf though at some point even though i will stop to ask for more features from now on. let him work on more features, someone will come and fork this app someday for updated gui ;)

**Comment by Amin456789** [comment]
@saddam213 
for a last request. could u please before stopping wpf updates make the batch count update please? i just said i won't have ask for more features yet i failed lol truly sorry man but after using batch count for a long time it is a bit hard to always push the send button and look at the screen

**Comment by saddam213** [comment]
This issue is for the WebUI, not WPF.

**Comment by james-s-tayler** [comment]
I'm definitely keen on an API, but tbh it depends on what the projects goals are or what you aspire for them to be. Is OnnxStack primarily a C# library that developers can use to build generative AI applications in whatever platform/framework suits their goals/needs, or is it more intended to be a Windows-based UI for Stable Diffusion? 

Those are two quite different things. 

The way I see it, if you build a great library, that unlocks the possibility for lots more C# developers to take that library and build out applications based on it however they see fit, though I recognize it's probably useful to build a UI as a way to dogfood your own library. At minimum it's probably worth it to focus on a single UI rather than try to split the projects limited engineering bandwidth across multiple UIs keeping them in sync.

**Comment by saddam213** [comment]
The project goal was ImageClassification, LOL, have not even got close to that part yet, got hooked on SD

The base projects are my goal and the the WebUI was added for users to test as the first user at the time was a Mac user I started with the WebUI as it was the simplest cross-platform UI I could whip up.

But as more users came a basic windows UI was needed as well, however I really don't want to waste time on UI code, I would rather focus on core code, so an API would be better for me, then users can build their own interfaces.

I will continue the WPF UI here until it is superseded by a future app that will include the Text Generation functions from LLamaStack, but that's another story

So yeah, leaning towards a API as replacement for WebUI

**Comment by saddam213** [comment]
WebUI has been decommissioned
