### ISSUE TITLE
Pipeline: ControlNet support for Stable Diffusion, LCM and InstaFlow

### ISSUE THREAD

**Issue by korzen** [saddam213/OnnxStack#35]
ControlNet support for Stable Diffusion and LCM?

**Comment by saddam213** [comment]
Yes, this is on the roadmap, this is required for AnimatedDiff which is the next large chunk of work to add to OnnxStack

**Comment by saddam213** [comment]
PR #88 in now underway to add ControlNet support is now underway :)

https://github.com/saddam213/OnnxStack/pull/88
