### ISSUE TITLE
nuget 

### ISSUE THREAD

**Issue by ForserX** [saddam213/OnnxStack#4]
Hi. I wouldn't mind taking your backend from the SD to transfer my old UI. Have you thought about packaging your libraries?

**Comment by saddam213** [comment]
> Hi. I wouldn't mind taking your backend from the SD to transfer my old UI. Have you thought about packaging your libraries?

Hey There,

The repo is still new, but I do have nuget packages available

`OnnxStack.Core` this is use to handle the models, so it can be shared across other Onnx projects
`OnnxStack.StableDiffusion` this has the stable diffusion stuff, SD 1.4/1.5 only at the moment
https://www.nuget.org/packages?q=sa_ddam213

Both packages are a week old and dont have the new cool stuff I made this week, however I will be releasing package v0.4.0 tomorrow, that will have img2img and inpaint support

Let me know if you need anything specific to help you integrate :)

**Comment by ForserX** [comment]
I'm unlikely to find time for this in the next month anyway. As soon as I get there, I'll unsubscribe. Good luck in your development!
