### ISSUE TITLE
Pipeline: Support InstaFlow single step inference

### ISSUE THREAD

**Issue by saddam213** [saddam213/OnnxStack#44]
New pipeline to add, looks like should be easy to implement as it uses existing SD schedulers

https://github.com/gnobitab/InstaFlow

Reference incase someone else wants to pick this up before I get to it :)
https://github.com/gnobitab/InstaFlow/blob/main/code/pipeline_rf.py
Lines 655, 663, 665, and 672 is all we need by the looks of it

@TheyCallMeHex think you could look at converting this model to ONNX :)

**Comment by Amin456789** [comment]
this is very cool indeed! even though i tested it and its better to wait and have a dreamshaper or deliberate mix with it or a lora for it for much better human. it seems it only works as a base 1.5

@AshD can u and ur friend Jambay convert this to onnx please?

**Comment by TheyCallMeHex** [comment]
Converted to ONNX: https://huggingface.co/TheyCallMeHex/InstaFlow-0.9B-ONNX

**Comment by saddam213** [comment]
InstaFlow pipeline now implemented
