### ISSUE TITLE
[Bug] CUDA provider disappeared in 0.9.0

### ISSUE THREAD

**Issue by ke1ne** [saddam213/OnnxStack#46]
Hi, in 0.8.0 settings I had CUDA provider available. Just got 0.9.0, and there is no CUDA now:
<img width="181" alt="image" src="https://github.com/saddam213/OnnxStack/assets/8934421/733c76f3-1b49-435c-8bd2-3727df82e96e">
Did I break anything?
Thanks!

**Comment by saddam213** [comment]
Hi Ke1ne,

The CUDA and CoreML options were removed form the UI as they are never supported by the UI, and they were causing confusion

CUDA requires a different build with CUDA binaries and that is something I have not gotten to yet, we are still experiencing huge VRAM spikes with the CUDA provider.
https://github.com/saddam213/OnnxStack/pull/41

The nuget packages still support all ONNX providers including CUDA, this is just a limit on the UI build

**Comment by saddam213** [comment]
If you are compiling the UI code and want to use the Onnx CUDA package and just want the option back then  `App.xaml`  line 1980

**Comment by ke1ne** [comment]
> The CUDA and CoreML options were removed as they were never supported by the UI, and they were causing confusion

Oh. So now it's a correct variation. Thanks, got it!
