### ISSUE TITLE
how to use with onnx models that doesnt have tokenizer model onnx file

### ISSUE THREAD

**Issue by patientx** [saddam213/OnnxStack#8]
Only worked with lms model , other models load with tokenizer on app directory "load" but doesnt do anything

**Comment by Amin456789** [comment]
there is one cliptokenizer.onnx in  onnxstack folder, i think u can use it for all of the models

**Comment by Amin456789** [comment]
u should get the new version, there is a high chance fp16 support is fixed ur issue, i had same issue it loaded lcm fp16 but didn't generate anything, not it is fixed.
maybe u should tell about the model u r using, is it fp32 or 16? how did u converted it, and the guys here will help u

**Comment by patientx** [comment]
I've written this to discussion but let me rewrite here, It seems there is one other difference with my local models, one big model.onnx file instead of small model.onnx and a large model.onnx_data file which is present on downloaded models.

**Comment by Amin456789** [comment]
this is something i noticed too, they are different somehow, for example i tried to quantize lyriel and deliberate [the one that u can get here] and it didn't work, but the epicrealism one worked. aside from chance i do believe u need to find the diffuser or safetensors of that model u want and reconvert it again with the updated scripts that use new onnx or something. 

@TheyCallMeHex  can u please tell how did u converted the models here so patientx can convert the older models that he wants?
